name = "portfolio-website"
compatibility_date = "2023-12-01"

[build]
command = "npm run build"
output_directory = ".next"

[site]
bucket = ".next"

[env.production]
routes = [
  { pattern = "/*", zone_name = "portfolio-website" }
]

[build.upload]
format = "service-worker"
